### ISSUE TITLE
unable to run `await shell.execute()`

### ISSUE THREAD

**Issue by XxWirusonxX** [louislefevre/node-red-contrib-quantum#28]
### Bug Description

Unable to run `await shell.execute()` while using Window OS.

### Steps to Reproduce Bug

start up NODE-RED, Put in and link nodes as following order: 
`inject` -> `quantum circuit` -> `quantum register` -> `debug`
![image](https://user-images.githubusercontent.com/12209829/125988012-a0c2bb28-237b-488b-a895-5b35eabf7660.png)

numbers of quantum circuit and register doesnt matter, but i have the following settings:
`quantum circuit`: `register and bits` = 1;
`quantum register`: `number of qubits` = 1;
deploy and press the button next to `inject` (timestamp)

Error Occur.

### Expected Behaviour & Actual Behaviour

Expected Behaviour: work without error. and should have debug output.

Actual Behaviour: Pop error in Console and no any debug output.
![image](https://user-images.githubusercontent.com/12209829/125988097-08bdab6d-f764-41f0-b30f-c050b91907c4.png)

### Additional Information

Temporily Fixed by comment out all the `await shell.execute()`.

### System Information

* **Node.js Version**: 14.17.1
* **Operating System**: Microsoft Windows NT 10.0.19042.0 x64

**Comment by louislefevre** [comment]
This is because the path for the Python executable in the virtual environment is set to the Unix path (`venv/bin/python`) by default, not the Windows path (`venv/Scripts/python.exe`). I haven't gotten around to implementing a check for the OS when setting the path just yet, so I'll do that this weekend. In the mean time, try change the line of code [here](https://github.com/louislefevre/node-red-contrib-quantum/blob/eb5ac5210bf832d10d4df9d18aa9018f40f04802/quantum/python.js#L8) to `const pythonPath = path.resolve(appRoot, 'venv/Scripts/python.exe');`. Just don't commit this change, please.

**Comment by XxWirusonxX** [comment]
After replacing the recommend LOC I have to following errors while execute the button in timestamp.
![image](https://user-images.githubusercontent.com/12209829/126063148-86a3de2a-64a3-4dbc-b526-432588f8a906.png)

**Comment by louislefevre** [comment]
> After replacing the recommend LOC I have to following errors while execute the button in timestamp.
> \<image>

Are you executing the `IMPORTS` snippet in your code?
